# Generated by Django 5.2 on 2025-11-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0006_photo_price_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='session_covers/'),
        ),
    ]
