# Generated by Django 5.2 on 2025-11-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0007_session_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='session',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_session', to='fotoapp.photo'),
        ),
    ]
